version: '2.4'

services:
  app:
    platform: linux/amd64
    ports:
      - "80:8000"
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ${PROJECT_PREFIX}_app
    volumes:
      - .:/app
    restart: unless-stopped
